services:

  - type: web

    name: communication-scorer

    runtime: python

    repo: https://github.com/AayushKulkarni36/Semantic-Communication-Scorer

    branch: main

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python -m spacy download en_core_web_sm

    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT

    envVars:

      - key: PYTHON_VERSION

        value: 3.11.0

      - key: PIP_DEFAULT_TIMEOUT

        value: 300

    plan: free

